# Generated by Django 4.2.1 on 2024-06-07 03:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pp_master', '0004_alter_location_warehouse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sys_dict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(default=1)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp_master.component')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp_master.location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp_master.warehouse')),
            ],
            options={
                'db_table': 'ld_stock_items',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockOutBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('bill_no', models.CharField(max_length=32)),
                ('out_date', models.DateField(default=datetime.date(2024, 6, 7))),
                ('components', models.ManyToManyField(to='ld_stock.stockitems')),
                ('out_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('out_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_dict.sysenum')),
            ],
            options={
                'db_table': 'ld_stock_out_bill',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockInBill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('bill_no', models.CharField(max_length=32)),
                ('in_date', models.DateField(verbose_name=datetime.date(2024, 6, 7))),
                ('components', models.ManyToManyField(to='ld_stock.stockitems')),
                ('in_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('in_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_dict.sysenum')),
            ],
            options={
                'db_table': 'ld_stock_in_bill',
                'abstract': False,
            },
        ),
    ]
