# Generated by Django 4.2.1 on 2024-06-07 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ld_stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinbill',
            name='in_date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 6, 7, 3, 24, 11, 379345, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='stockoutbill',
            name='out_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 7, 3, 24, 11, 383334, tzinfo=datetime.timezone.utc)),
        ),
    ]
