# Generated by Django 4.2.1 on 2024-06-07 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ld_stock', '0002_alter_stockinbill_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinbill',
            name='in_date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockoutbill',
            name='out_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
