# Generated by Django 4.2.1 on 2024-05-21 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_dep', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=512)),
                ('code', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=128, null=True)),
                ('phone', models.CharField(max_length=24, null=True)),
                ('photo_path', models.CharField(max_length=128, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_dep.department')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'org_employee',
                'abstract': False,
            },
        ),
    ]
