# Generated by Django 4.2.1 on 2024-05-24 06:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pp_master', '0002_alter_productworkcenter_line'),
        ('org_emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='pp_master.productworkcenter'),
        ),
        migrations.CreateModel(
            name='EmloyeeWorkCenterChangeList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_center_list', to='org_emp.employee')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_list', to='pp_master.productworkcenter')),
            ],
            options={
                'db_table': 'employee_work_center_change_list',
                'abstract': False,
            },
        ),
    ]
