# Generated by Django 4.2.1 on 2024-05-24 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp_master', '0002_alter_productworkcenter_line'),
        ('org_emp', '0002_employee_work_center_emloyeeworkcenterchangelist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmloyeeWorkCenterChangeList',
            new_name='EmployeeWorkCenterChangeList',
        ),
    ]
