# Generated by Django 4.2.1 on 2024-05-21 06:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org_com', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=512)),
                ('code', models.CharField(max_length=32)),
                ('is_pp_rel_dept', models.BooleanField(default=False)),
                ('is_pp_dept', models.BooleanField(default=False)),
                ('is_hv_dept', models.BooleanField(default=False)),
                ('is_qc_dept', models.BooleanField(default=False)),
                ('is_an_handle_dept', models.BooleanField(default=False)),
                ('is_wk_handle_dept', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_com.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='org_dep.department')),
            ],
            options={
                'db_table': 'org_department',
                'abstract': False,
            },
        ),
    ]
