# Generated by Django 4.2.1 on 2024-05-21 06:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sys_dict', '0001_initial'),
        ('org_com', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=8)),
                ('model_sap', models.CharField(blank=True, max_length=128, null=True)),
                ('model_mes', models.CharField(blank=True, max_length=128, null=True)),
                ('pro_group1', models.CharField(blank=True, max_length=128, null=True)),
                ('pro_group2', models.CharField(blank=True, max_length=128, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_codes', to='org_com.company')),
            ],
            options={
                'db_table': 'pp_machine_code',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=128)),
                ('brand_code', models.CharField(blank=True, max_length=64, null=True)),
                ('weight_sap', models.IntegerField(default=0)),
                ('weight_brand', models.IntegerField(default=0)),
                ('engine_no', models.CharField(blank=True, max_length=128, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('product', models.BooleanField(default=False)),
                ('cup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cups', to='sys_dict.sysenum')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org_com.company')),
                ('machine_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp_master.machinecode')),
                ('machine_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mts', to='sys_dict.sysenum')),
                ('sale_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sts', to='sys_dict.sysenum')),
            ],
            options={
                'db_table': 'pp_model_code',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionBasic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=24)),
                ('sequence', models.CharField(max_length=24)),
                ('use', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='org_com.company')),
            ],
            options={
                'db_table': 'pp_option_basic',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=24)),
                ('code', models.CharField(max_length=8)),
                ('version', models.CharField(max_length=4)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lines', to='org_com.company')),
            ],
            options={
                'db_table': 'pp_product_line',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductWorkCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=128)),
                ('to_track', models.BooleanField(default=False)),
                ('to_sap', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sys_dict.sysenum')),
                ('end_wc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_workcenter', to='pp_master.productworkcenter')),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_centers', to='org_com.company')),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pp_master.productline')),
                ('start_wc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_workcenter', to='pp_master.productworkcenter')),
            ],
            options={
                'db_table': 'pp_work_center',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=48)),
                ('style_code', models.CharField(max_length=16)),
                ('o_sap', models.CharField(max_length=256)),
                ('s_sap', models.CharField(max_length=256)),
                ('o_mes', models.CharField(max_length=256)),
                ('s_mes', models.CharField(max_length=256)),
                ('basic', models.BooleanField(default=False)),
                ('erp_if', models.BooleanField(default=True)),
                ('sign', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_codes', to='org_com.company')),
                ('model_styles', models.ManyToManyField(related_name='options', to='pp_master.modelcode')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp_master.optionbasic')),
            ],
            options={
                'db_table': 'pp_option_code',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='machinecode',
            name='lines',
            field=models.ManyToManyField(to='pp_master.productline'),
        ),
        migrations.AddField(
            model_name='machinecode',
            name='pro_quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_dict.sysenum'),
        ),
    ]
