# Generated by Django 4.2.1 on 2024-05-22 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productworkcenter',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_centers', to='pp_master.productline'),
        ),
    ]
