# Generated by Django 4.2.1 on 2024-06-03 06:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sys_dict', '0001_initial'),
        ('org_com', '0001_initial'),
        ('pp_master', '0002_alter_productworkcenter_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('safe_storage', models.IntegerField(default=1)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='org_com.company')),
            ],
            options={
                'db_table': 'pp_component',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=512)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='org_com.company')),
            ],
            options={
                'db_table': 'pp_warehouse',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('code', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=128)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp_master.warehouse')),
            ],
            options={
                'db_table': 'pp_location',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentInOutList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('sign', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(default=0)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inouts', to='pp_master.component')),
                ('inout_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_dict.sysenum')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp_master.location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp_master.warehouse')),
            ],
            options={
                'db_table': 'pp_component_inout_list',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentAmount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_by', models.IntegerField(null=True)),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField(default=1)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amounts', to='pp_master.component')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp_master.location')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pp_master.warehouse')),
            ],
            options={
                'db_table': 'pp_component_amount',
                'abstract': False,
            },
        ),
    ]
