# Generated by Django 4.2.1 on 2024-06-07 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pp_master', '0003_component_warehouse_location_componentinoutlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='pp_master.warehouse'),
        ),
    ]
